import { BRAND } from "@/lib/brand";

export default function PrivacyPage() {
  return (
    <>
      <section className="gov-banner py-10 md:py-14">
        <div className="container mx-auto px-4 text-center max-w-3xl">
          <h1 className="font-heading text-3xl md:text-4xl font-bold">Privacy Policy</h1>
        </div>
      </section>
      <article className="container mx-auto px-4 py-12 max-w-3xl space-y-6 text-sm leading-relaxed">
        <p>
          This Privacy Policy (&quot;Policy&quot;) applies to {BRAND.name} and outlines the principles and
          practices regarding the use of the website located at {BRAND.domain} (&quot;Website&quot;). The Website
          is owned and managed by {BRAND.legalEntity.endsWith(".") ? BRAND.legalEntity : `${BRAND.legalEntity}.`} By accessing, using, engaging, registering, recommending,
          or linking to the Website, you consent to these terms. If you do not agree with any part of these terms,
          you are advised not to use our Website.
        </p>
        <p>
          {BRAND.name} is a consultancy assistance platform, independent and not affiliated with, endorsed by,
          sponsored, or supported by any government or regulatory body. We provide independent consultancy
          services, and our services, information, or guidance should not be considered officially linked or
          endorsed by any governmental agency.
        </p>

        <section>
          <h2 className="font-heading text-lg font-bold mb-2">1. Definitions</h2>
          <ul className="list-disc pl-5 space-y-1">
            <li>
              <strong>Services</strong> refer to providing independent assistance and streamlining the application
              process for obtaining Fishing Licences.
            </li>
            <li>
              <strong>Personal Data</strong> is information about a living individual who can be identified from
              those data.
            </li>
            <li>
              <strong>Usage Data</strong> is data collected automatically, generated by the use of the Service or
              from the Service infrastructure itself.
            </li>
            <li>
              <strong>Cookies</strong> are small files stored on your device (computer or mobile device).
            </li>
            <li>
              <strong>Data Controller</strong> is a natural or legal person who determines the purposes and manner
              in which any personal data are processed. For this Privacy Policy, we are the Data Controller of
              your data.
            </li>
            <li>
              <strong>Service Provider</strong> refers to any natural or legal person who processes the data on
              behalf of the Data Controller.
            </li>
            <li>
              <strong>Data Subject</strong> is any living individual who is the subject of Personal Data.
            </li>
            <li>
              <strong>The User</strong> is the individual using our Service, corresponding to the Data Subject.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="font-heading text-lg font-bold mb-2">Commitment to Your Privacy</h2>
          <p>
            {BRAND.name} deeply values your privacy. We adhere to the Personal Information Protection and
            Electronic Documents Act (PIPEDA), Canada&apos;s federal privacy law, as well as applicable provincial
            privacy laws. Additionally, we respect international privacy regulations such as the General Data
            Protection Regulation (GDPR) for European users and the California Consumer Privacy Act (CCPA) for
            users from California.
          </p>
        </section>

        <section>
          <h2 className="font-heading text-lg font-bold mb-2">Personal Data Collection</h2>
          <p>
            While interacting with our Website, you may be asked to provide certain personally identifiable
            information, which may include, but is not limited to:
          </p>
          <ul className="list-disc pl-5 mt-2 space-y-1">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Identification Documentation (e.g., passport, driver&apos;s licence)</li>
            <li>Address, Province, Postal code, City</li>
            <li>Cookies and Usage Data</li>
            <li>Bank and credit/debit card details, which may include billing address and identity details</li>
          </ul>
          <p className="mt-3">
            This information is collected to facilitate communication, identify you as a user of our Service, and
            tailor our assistance to your needs.
          </p>
        </section>

        <section>
          <h2 className="font-heading text-lg font-bold mb-2">Usage Data</h2>
          <p>
            We may collect information that your browser sends whenever you visit our Website, including your
            computer&apos;s Internet Protocol address (IP address), device type, unique device identifiers,
            operating system, and other diagnostic data.
          </p>
        </section>

        <section>
          <h2 className="font-heading text-lg font-bold mb-2">Tracking Cookies Data</h2>
          <p>
            We utilise cookies and similar tracking technologies to monitor activity on our Website and hold
            certain information. You can set your device to refuse all cookies or to indicate when a cookie is
            being sent. However, if you do not accept cookies, you might not be able to use some portions of our
            Website.
          </p>
        </section>

        <section>
          <h2 className="font-heading text-lg font-bold mb-2">Use of Data</h2>
          <p>{BRAND.name} uses the collected data for various purposes:</p>
          <ul className="list-disc pl-5 mt-2 space-y-1">
            <li>To offer and refine our Website and services.</li>
            <li>To inform you about alterations to our Website or service.</li>
            <li>To enable interactive Website features at your discretion.</li>
            <li>To provide customer support.</li>
            <li>For analytical insights to enhance our Website and Service.</li>
            <li>To oversee our Website and Service usage.</li>
            <li>To tackle technical challenges.</li>
            <li>For contractual obligations between us.</li>
            <li>For account and subscription-related notifications.</li>
            <li>To share relevant updates, promotions, or similar service offerings, unless you opt out.</li>
          </ul>
        </section>

        <section>
          <h2 className="font-heading text-lg font-bold mb-2">Security</h2>
          <p>
            {BRAND.name} prioritises the security of your data, implementing comprehensive physical, electronic,
            and administrative safeguards to protect your information from misuse, loss, unauthorised changes,
            access, or disclosure. Despite our stringent security measures, the inherent nature of online data
            transmission means that we cannot guarantee absolute security.
          </p>
        </section>

        <section>
          <h2 className="font-heading text-lg font-bold mb-2">Your Rights</h2>
          <p>
            Your rights regarding your data are of utmost importance to us. You can request to access, correct, or
            delete your personal information at any time by contacting us at {BRAND.email}.
          </p>
          <ul className="list-disc pl-5 mt-2 space-y-1">
            <li>
              <strong>Right to Access, Update, or Delete:</strong> You can access, correct, or request the deletion
              of your personal information.
            </li>
            <li>
              <strong>Right of Rectification:</strong> If any information is incomplete or inaccurate, you have the
              right to have it corrected.
            </li>
            <li>
              <strong>Right to Object:</strong> You can object to our processing of your Personal Data.
            </li>
            <li>
              <strong>Right of Restriction:</strong> You can ask us to limit the processing of your data.
            </li>
            <li>
              <strong>Right to Data Portability:</strong> At your request, we can provide your data in a commonly
              used, structured, and machine-readable format.
            </li>
            <li>
              <strong>Right to Withdraw Consent:</strong> If we are processing data based on your consent, you can
              withdraw that consent at any time.
            </li>
          </ul>
          <p className="mt-3">
            We may request proof of identity before fulfilling your requests to ensure the security of your data.
          </p>
        </section>

        <section>
          <h2 className="font-heading text-lg font-bold mb-2">Privacy Complaints</h2>
          <p>
            If you have any concerns or complaints regarding our handling of privacy, please reach out to us at{" "}
            {BRAND.email}. Addressing and resolving your concerns swiftly is our priority.
          </p>
        </section>

        <section>
          <h2 className="font-heading text-lg font-bold mb-2">Opt-Out Right</h2>
          <p>
            If you decide to stop all data collection activities by {BRAND.name}, you may communicate your opt-out
            preference to us via email at {BRAND.email}.
          </p>
        </section>

        <section>
          <h2 className="font-heading text-lg font-bold mb-2">Changes to Policy</h2>
          <p>
            We reserve the right to modify this privacy policy as necessary. Changes will take effect immediately
            upon their posting on our platform. We encourage you to review our policy periodically.
          </p>
        </section>

        <section>
          <h2 className="font-heading text-lg font-bold mb-2">Children&apos;s Privacy</h2>
          <p>
            {BRAND.name} is not designed for children under the age of 15, and we do not knowingly collect
            personal data from children without parental consent. If you believe a child under 15 has provided us
            with personal data, please contact us at {BRAND.email}.
          </p>
        </section>

        <section>
          <h2 className="font-heading text-lg font-bold mb-2">Contact Us</h2>
          <p>
            For any questions, feedback, or concerns regarding our Privacy Policy, please reach out to us at{" "}
            {BRAND.email}. To help us address your inquiry efficiently, please include a specific subject line,
            such as &quot;Accessing Personal Data.&quot;
          </p>
        </section>
      </article>
    </>
  );
}
